### PR TITLE
CronJob minimum resource allocations

### PR DESCRIPTION
**Pull request by gkarthiks**
**Issue Ref**: Fixes https://github.com/kubeless/cronjob-trigger/issues/4
 
**Description**: 
Adding the minimum resource as below to pass through the quota restrictions of the namespace for the trigger pod initialization. Background provided in the following issues:
- https://github.com/kubeless/cronjob-trigger/issues/4
- https://github.com/kubeless/kubeless/issues/960
```diff
+ 	Resources: v1.ResourceRequirements{
+		Limits: v1.ResourceList{
+			v1.ResourceMemory: resource.MustParse("32Ki"),
+			v1.ResourceCPU:    resource.MustParse("1m"),
+		},
+		Requests: v1.ResourceList{
+			v1.ResourceMemory: resource.MustParse("32Ki"),
+			v1.ResourceCPU:    resource.MustParse("1m"),
+		},
+	},
```

**TODOs**:
 - [X] Ready to review
 - [x] Automated Tests
 - [ ] Docs

### CODE REVIEW

**Comment by andresmgot** [comment]
Hi @gkarthiks, thanks for the PR!

Do you mind to rebase master to fix the issue with the CI?

Also, how did you choose the values for the memory and CPU? Does it work properly for you? (`1m` for CPU seems a bit low)

**Comment by gkarthiks** [comment]
@andresmgot  yeah, so this trigger pods functionality is nothing but to just execute a `curl` command I chose that minimal value.

On OpenShift with my observations, this trigger pod doesn't even utilize 1m core of cpu and 32Ki of memory. But if you suggest any other number I will update that.

**Comment by andresmgot** [comment]
Hi @gkarthiks,

It seems that in the CI (minikube) the job pods are not being created. The reason is the following:

```
    state:
      waiting:
        message: 'Error response from daemon: Minimum memory limit allowed is 4MB'
        reason: CreateContainerError
```

It seems that the minimum amount of memory is 4MB, at least for the version we have in the CI:

https://github.com/kubernetes/kubernetes/issues/49442#issuecomment-320848399

Do you mind increasing the minimum memory to that value?

**Comment by gkarthiks** [comment]
Hi @andresmgot, changed the memory as requested.

**Review by andresmgot — APPROVED** [review]
Cool, thanks!

**Pull request merged**
